### PR TITLE
Support for OpenSSL up to 3.1.x

### PR DESCRIPTION
**Pull request by fferino-fungible**

### CODE REVIEW

**Comment by fferino-fungible** [comment]
@TrinityTonic it's difficult to be 100% sure what is going on with your build. 

However, if you look for the variables that are  are reported as multiply defined, they are in the header file with an EXTERN macro : https://github.com/microsoft/ms-tpm-20-ref/blob/f74c0d9686625c02b0fdd5b2bbe792a22aa96cb6/TPMCmd/Platform/include/PlatformData.h#L56.

And this EXTERN macro maps either to nothing or to the "extern" C keyword depending on whether the macro _PLATFORM_DATA_C_ is defined. https://github.com/microsoft/ms-tpm-20-ref/blob/f74c0d9686625c02b0fdd5b2bbe792a22aa96cb6/TPMCmd/Platform/include/PlatformData.h#L41

So depending on how you build the TPM library, you will either have one, many or no definitions of these variables in your build of the TPM library. In your case, you seem to have either multiple definitions or at least one with another definition provided with the other components in your link so _PLATFORM_DATA_C_ was defined in your build of the TPM library.

I would try first to rebuild the library with _PLATFORM_DATA_C_ undefined.

It will either fix the problem (the variables are provided by another component of your build) or you will get an "undefined" or "missing definition" link error. If the latter, then your toolchain treats uninitialized global variables as common symbols (cf. the "Mac OS X build" of the README.md) https://github.com/microsoft/ms-tpm-20-ref/blob/main/README.md#mac-os-x-build and you will need to change your compiler/linker flags. 

I hope this helps.

**Comment by wxleong** [comment]
Any plan to accept this PR?

**Comment by bradlitterell** [comment]
Our plan is to update this repo with the next public version of the code which is currently being worked on which has a similar change.

**Comment by wxleong** [comment]
Any estimated timeframe for this public release?

**Pull request closed without merging**
