### PR TITLE
Add simulator samples to derive EPS seed from device hardware parameters

### PR DESCRIPTION
**Pull request by mohandatla**
-add optional macro to specify custom file location.
-add optional macro to derive EPS seed from hardware parameters.
-linux only changes.

### CODE REVIEW

**Comment by mohandatla** [comment]
>     6\. Mem.c restore capital 'C' in the default "NVchip" name.

Thanks Andrey for the code review. Fixed your comments. 
1. In your review you are refer to LOG_ERROR, Is that means LOG_FAILURE macro only right or something else.
2. Added FATAL_ERROR_DEVICEID custom error code for future diagnostic extension purpose.

**Comment by amarochk** [comment]
Meanwhile I've manually added "void _plat__GetEPS(UINT16, BYTE*)" prototype to the platform_fp.h. So as soon as you fix copying, everything should work.

**Comment by mohandatla** [comment]
> rect _plat__GetEPS prototype in the platform_fp.h header. So, your build script needs to make sure that the EPS.c is not copied over from the main source tree. One way to do this is to rename your deviceID.c to EPS.c and use '-n' option for the 'cp' command. Or you can explicitly exclude it from cop

Thank you for your review. Fixed and validated with -n it looks good.

**Comment by mohandatla** [comment]
> Meanwhile I've manually added "void _plat__GetEPS(UINT16, BYTE*)" prototype to the platform_fp.h. So as soon as you fix copying, everything should work.

Thanks Andrey, Picked up your change from parent repo and removed the change in my PR.

**Pull request merged**
